name: Release Assets

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  setup_buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2  

  build_acapy:
    needs: setup_buildx
    name: 'Build Traction Aca-Py'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Build Aca-Py Image
        uses: ./.github/actions/build_acapy
        id: builder
        with:
          context: './plugins'
          dockerfile: './plugins/docker/Dockerfile'
          platforms: linux/amd64,linux/arm64
          image_name: ${{ github.repository_owner}}/traction-plugins-acapy
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

  build_ui:
    needs: setup_buildx
    name: 'Build Tenant UI'
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Build UI
        uses: ./.github/actions/build_ui
        id: builder
        with:
          context: './services/tenant-ui'
          platforms: linux/amd64,linux/arm64
          image_name: ${{ github.repository_owner}}/traction-tenant-ui
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
  
  build_proxy:
    needs: setup_buildx
    name: 'Build Tenant Proxy Image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Tenant Proxy Image
        uses: ./.github/actions/build_acapy
        id: builder
        with:
          context: './plugins'
          dockerfile: './plugins/docker/Dockerfile.tenant-proxy'
          platforms: linux/amd64,linux/arm64
          image_name: ${{ github.repository_owner}}/traction-tenant-proxy
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
