name: Release ARM64 Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for arm64
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: your-docker-repo/your-image-name:latest, your-docker-repo/your-image-name:${{ github.sha }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Docker Image Info
      uses: actions/upload-artifact@v3
      with:
        name: arm64-docker-image-info
        path: |
          ./Dockerfile
          ./path/to/other/relevant/files
