name: Staging Release Assets

on:
  push:
    tags:
      - 'staging-v*'
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build_acapy:
    name: 'Build Traction Aca-Py Staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    
      - name: Build Aca-Py Image
        uses: ./.github/actions/build_acapy
        id: builder
        with:
          context: './plugins'
          dockerfile: './plugins/docker/Dockerfile'
          image_name: ${{ github.repository_owner}}/traction-plugins-acapy-v1.0.1-staging
          platform: linux/amd64, linux/arm64
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

  build_ui:
    name: 'Build Tenant UI Staging'
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Build UI
        uses: ./.github/actions/build_ui
        id: builder
        with:
          context: './services/tenant-ui'
          image_name: ${{ github.repository_owner}}/traction-tenant-ui-v1.0.1-staging
          platform: linux/amd64, linux/arm64
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
  
  build_proxy:
    name: 'Build Tenant Proxy Staging Image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Tenant Proxy Image
        uses: ./.github/actions/build_acapy
        id: builder
        with:
          context: './plugins'
          dockerfile: './plugins/docker/Dockerfile.tenant-proxy'
          image_name: ${{ github.repository_owner}}/traction-tenant-proxy-v1.0.1-staging
          platform: linux/amd64, linux/arm64
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }} 