# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test Tenant UI

on:
  pull_request:
    branches: ["main"]
    paths:
      - "/plugins/traction_innkeeper/traction_innkeeper/**"

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/traction_innkeeper

    steps:
      #----------------------------------------------
      #       Check out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      #----------------------------------------------
      #       Install python and poetry with cache
      #----------------------------------------------
      - name: Install poetry
        run: pipx install poetry==1.8.3
        id: setup-poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      #----------------------------------------------
      #       Install dependencies
      #----------------------------------------------
      - name: Install dependencies
        id: install-dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --all-extras
      #----------------------------------------------
      #       Lint plugins
      #----------------------------------------------
      - name: Lint plugins
        id: lint-plugins
        run: poetry run ruff check .
      #----------------------------------------------
      #       Unit tests
      #----------------------------------------------
      - name: Unit test plugins
        id: unit-tests
        run: poetry run pytest
