name: Traction Agent Release

on:
  push:
    tags:
      - 'agent-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (e.g. 1.0.1-20250101)'
        required: true

permissions:
  packages: write
  contents: write

jobs:
  build_traction_agent:
    name: 'Build Traction Agent'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set version and lowercase owner
        id: set_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            # Extract version from tag (remove 'agent-v' prefix)
            TAG=${GITHUB_REF#refs/tags/agent-v}
            echo "VERSION=${TAG}" >> $GITHUB_OUTPUT
          fi
          # Convert repository owner to lowercase for Docker tags
          echo "OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
      - name: Build and Push Plugins AcaPy Image
        uses: docker/build-push-action@v6
        with:
          context: ./plugins
          file: ./plugins/docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.set_version.outputs.OWNER_LOWERCASE }}/traction-plugins-acapy:latest
            ghcr.io/${{ steps.set_version.outputs.OWNER_LOWERCASE }}/traction-plugins-acapy:${{ steps.set_version.outputs.VERSION }}
      
      - name: Temporarily modify Dockerfile.acapy to use GHCR image
        run: |
          sed -i "s|FROM --platform=\$BUILDPLATFORM traction:plugins-acapy|FROM --platform=\$BUILDPLATFORM ghcr.io/${{ steps.set_version.outputs.OWNER_LOWERCASE }}/traction-plugins-acapy:latest|" ./services/aca-py/Dockerfile.acapy
      
      - name: Build and push Traction Agent
        uses: docker/build-push-action@v6
        with:
          context: ./services/aca-py
          file: ./services/aca-py/Dockerfile.acapy
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.set_version.outputs.OWNER_LOWERCASE }}/traction-agent:latest
            ghcr.io/${{ steps.set_version.outputs.OWNER_LOWERCASE }}/traction-agent:${{ steps.set_version.outputs.VERSION }} 